[APP]
# Extension must me seed-me
SITEMAP_URL = "https://www.hellofresh.seed-me/sitemap_recipe_pages.xml"
USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
pdf_save_path = "YOUR_PATH_HERE/ressources/seed-me.pdf"

[DATABASE]
URL = "https://localhost:9200"
USERNAME = "elastic"
PASSWORD = "elastic"
# Must be one of "elasticSearch" or "mongoDB"
TYPE = "elasticSearch"